// SPDX-License-Identifier: MIT
pragma solidity >=0.8.9;
import "./IParent.sol";

/**
 * @dev Entity deployer.
 */
interface IEntityDeployer is IParent {
    /**
     * @dev Deploy a new entity.
     *
     * @param _entityAdmin Entity administrator.
     * @param _entityContext The ACL context to set for the entity. If ommitted then a default one will be auto-generated by the entity.
     */
    function deploy(address _entityAdmin, bytes32 _entityContext) external;

    /**
     * @dev Emitted when a new entity has been created.
     * @param entity The entity address.
     * @param deployer The person who deployed it.
     */
    event NewEntity(address indexed entity, address indexed deployer);
}
