pragma solidity >=0.6.7;

/**
 * @dev Settings keys.
 */
contract ISettingsKeys {
  // BEGIN: Generated by script outputConstants.js
  // DO NOT MANUALLY MODIFY THESE VALUES!
  bytes32 constant public SETTING_MARKET = 0x6f244974cc67342b1bd623d411fd8100ec9eddbac05348e71d1a9296de6264a5;
  bytes32 constant public SETTING_ENTITY_IMPL = 0x098afcb3a137a2ba8835fbf7daecb275af5afb3479f12844d5b7bfb8134e7ced;
  bytes32 constant public SETTING_POLICY_IMPL = 0x0e8925aa0bfe65f831f6c9099dd95b0614eb69312630ef3497bee453d9ed40a9;
  bytes32 constant public SETTING_ENTITY_DEPLOYER = 0x1bf52521006d8a3718b0692b7f32c8ee781bfed9e9215eb5b8fc3b34749fb5b5;
  bytes32 constant public SETTING_NAYMS_ENTITY = 0x329d39dd85dee2a8a3da2fd96bac52d7faa7def7f2e0a4598588eb7acda966b5;
  // END: Generated by script outputConstants.js
}
