pragma solidity >=0.5.8;

/**
 * @dev Settings keys.
 */
contract ISettingsKeys {
  // BEGIN: Generated by script outputConstants.js
  // DO NOT MANUALLY MODIFY THESE VALUES!
  bytes32 constant public SETTING_MARKET = 0x00735eed6972307d0475953b452f6f2b35bd66ee0938bef314e633b88d3b927c;
  bytes32 constant public SETTING_POLICY_IMPL = 0xe240fbdf420a3dbd32c5a399c231c5224c0012d1bc870229cf36b2dc8c0105dd;
  bytes32 constant public SETTING_POLICY_CLAIMS_IMPL = 0xae9e00b361d207acd9f454e0b78edd5198ec9857a405927277dfefc45ffe8a00;
  bytes32 constant public SETTING_POLICY_COMMISSIONS_IMPL = 0x5abfdf693fa60e6a5f1c3db1fc865a85c6ac2567eac94abc18e38fb98fa350ce;
  bytes32 constant public SETTING_POLICY_PREMIUMS_IMPL = 0xd08788d2e1403121dbf414aeabd657f969bbb663d86fb3684d99b0e1429e7079;
  bytes32 constant public SETTING_ENTITY_DEPLOYER = 0xd1d226c710b6885a69e38588aa34e8fcd7fbb408056c69e688d336fd5dc23b3c;
  bytes32 constant public SETTING_NAYMS_ENTITY = 0x6bdcced030cf59efef887b3b5e52116a9ceb32f7e45bd2424fd899dc92982af3;
  // END: Generated by script outputConstants.js
}

